### ISSUE TITLE
Error 0xa8 on line 1954115647. Pulling sounds from database

### ISSUE THREAD

**Issue by AlzoPalzo** [gosu/gosu#486]
Trying to assign a sample to trigger with keyboard buttons. The sounds need to come from a database object that maps sound file paths to specific sound "Kits" When the file path is hard coded or a new object is instantiated  before being pushed to the database it runs fine. If the object is created from data already in the database it throws the error in the title.

The error

```
`/Users/flatironschool/.rvm/gems/ruby-2.3.3/gems/gosu-0.14.5/lib/gosu/compat.rb:115:in `initialize': Error 0xa8 on line 1954115647: The operation couldn’t be completed. (OSStatus error 1954115647.) (RuntimeError)
        from /Users/flatironschool/.rvm/gems/ruby-2.3.3/gems/gosu-0.14.5/lib/gosu/compat.rb:115:in `initialize'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/window/window.rb:7:in `new'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/window/window.rb:7:in `initialize'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/window/window.rb:39:in `new'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/window/window.rb:39:in `initialize'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/models/user.rb:47:in `new'
        from /Users/flatironschool/ali_flatiron/Final-project-mod-1/app/models/user.rb:47:in `play_kit'
        from bin/run.rb:49:in `<main>'`
```

Error occurs here
```ruby
    def initialize(sp1, sp2 ,sp3, sp4)
        @s1 =Gosu::Sample.new(@sp1)
        @s2 =Gosu::Sample.new(@sp2)
        @s3 =Gosu::Sample.new(@sp3)
        @s4 =Gosu::Sample.new(@sp4)        
    end
```

Variables come from here

```ruby 
  def my_kits
      Kit.where(user_id: self.id)
  end

  def kitsounds_from_kit(this_kit)
    Kitsound.where(kit_id: this_kit.id)
  end

        kit = my_kits[0]
        my_kitsounds = kitsounds_from_kit(kit)
        ks1 = my_kitsounds[0]
        sp1 = Sound.find(ks1.sound_id).sound_path
        ks2 = my_kitsounds[1]
        sp2 = Sound.find(ks2.sound_id).sound_path
        ks3 = my_kitsounds[2]
        sp3 = Sound.find(ks3.sound_id).sound_path
        ks4 = my_kitsounds[3]
        sp4 = Sound.find(ks4.sound_id).sound_path
        # binding.pry
        My_window.new(self.name, kit.name, sp1, sp2, sp3, sp4).show

class My_window < Gosu::Window
    def initialize(username, kit_name, sp1, sp2, sp3, sp4)
        super 640, 480
        self.caption = "#{username}'s #{kit_name}"
        @user_kit = User_kit.new(sp1, sp2, sp3, sp4)
    end
```

<sup>Edit by Kjarrigan - Make it actual code blocks for better readability</sup>

**Comment by Kjarrigan** [comment]
Is this really the code you're using? There is an obvious error here:

```ruby
def initialize(sp1, sp2 ,sp3, sp4)
        @s1 =Gosu::Sample.new(@sp1)
        @s2 =Gosu::Sample.new(@sp2)
        @s3 =Gosu::Sample.new(@sp3)
        @s4 =Gosu::Sample.new(@sp4)        
    end
```

That can't work. It has to be: 

```ruby
def initialize(sp1, sp2 ,sp3, sp4)
        @s1 =Gosu::Sample.new(sp1)
        @s2 =Gosu::Sample.new(sp2)
        @s3 =Gosu::Sample.new(sp3)
        @s4 =Gosu::Sample.new(sp4)        
    end
```
because @sp1 is nil (your argument is named sp1, without the @) so it basically is a 

```ruby
        @s1 =Gosu::Sample.new(nil)
```
call, BUT this should throw this error:

```
~/.rvm/gems/ruby-2.5.1/gems/gosu-0.14.5/lib/gosu/compat.rb:115:in `initialize': Cannot open file  (RuntimeError)
```

**Comment by AlzoPalzo** [comment]
Hi thank you for responding. Actually the code was originally how you wrote. Posted the wrong version.  We were going crazy trying to figure out what was causing the error and started doing all sorts of weird things to the code. We've actually just decided to rewrite all the relevant code as it was just becoming a mess. Thank you

**Comment by Kjarrigan** [comment]
Ok - closing. Reopen with the updated code if the issue persists.
