### ISSUE TITLE
RMagick intergration not working

### ISSUE THREAD

**Issue by urbima** [gosu/gosu#680]
Gosu RMagick integration seems to be broken for me now, running ImageMagick 7.1.1.36-1, RMagick 6.0.1 and Gosu 1.4.6 on Arch Linux. When I try to run rmagick_integration.rb from gosu-examples I get this: 
```
rmagick_integration.rb:68:in 'block in <class:Map>': undefined method 'background_color=' for Map:Class (NoMethodError)
	from rmagick_integration.rb:68:in 'initialize'
	from rmagick_integration.rb:68:in 'new'
	from rmagick_integration.rb:68:in '<class:Map>'
	from rmagick_integration.rb:29:in '<main>'
```
 The same seems to happen for any block that follows an RMagick object; for example the example from the documentation,
```ruby
magick_image = Magick::Image.from_blob(image.to_blob) {
  self.format = "RGBA"
  self.size = "#{image.width}x#{image.height}"
  self.depth = 8
}.first
```
gives the error
```
lesson01.rb:20:in `block in initialize': undefined method `format=' for #<Window:0x00005a5b0be7cc80 @__swigtype__="_p_Gosu__Window"> (NoMethodError)
Did you mean?  format
	from lesson01.rb:19:in `from_blob'
```

**Comment by cyberarm** [comment]
Does your block work if you use an instance variable in the block?
```ruby
magick_image = Magick::Image.from_blob(image.to_blob) { |b|
  b.format = "RGBA"
  b.size = "#{image.width}x#{image.height}"
  b.depth = 8
}.first
```

**Comment by urbima** [comment]
Actually it seems like it does work like that, but rmagick_integration.rb now gives me a new error:
```
(eval):1:in `block in initialize': undefined method `depth=' for media/landscape.svg RGBA 850x638 850x638+0+0 DirectClass 8-bit 23kb:Magick::Image (NoMethodError)
Did you mean?  depth
	from (eval):1:in `to_blob'
	from (eval):1:in `initialize'
	from /home/urbima/.local/share/gem/ruby/3.0.0/gems/gosu-1.4.6/lib/gosu/compat.rb:71:in `initialize'
	from /home/urbima/.local/share/gem/ruby/3.0.0/gems/gosu-1.4.6/lib/gosu/compat.rb:71:in `initialize'
	from rmagick_integration.rb:35:in `new'
	from rmagick_integration.rb:35:in `initialize'
	from rmagick_integration.rb:351:in `new'
	from rmagick_integration.rb:351:in `initialize'
	from rmagick_integration.rb:414:in `new'
	from rmagick_integration.rb:414:in `<main>'

```
